name: Create Release Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Check version change and create tag
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          
          # Get previous version from last commit
          git show HEAD~1:package.json > /tmp/previous.json 2>/dev/null || echo '{"version":"0.0.0"}' > /tmp/previous.json
          PREVIOUS_VERSION=$(node -p "JSON.parse(require('fs').readFileSync('/tmp/previous.json', 'utf-8')).version")
          
          echo "Current version: $CURRENT_VERSION"
          echo "Previous version: $PREVIOUS_VERSION"
          
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
            
            # Check if tag already exists
            if git rev-parse "v$CURRENT_VERSION" >/dev/null 2>&1; then
              echo "Tag v$CURRENT_VERSION already exists, skipping"
              exit 0
            fi
            
            # Create and push tag
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag -a "v$CURRENT_VERSION" -m "Release v$CURRENT_VERSION"
            git push origin "v$CURRENT_VERSION"
            echo "Created and pushed tag v$CURRENT_VERSION"
          else
            echo "Version unchanged, no tag created"
          fi
